### ISSUE TITLE
Can't pull image from private repository 

### ISSUE THREAD

**Issue by amenasse** [amenasse/antkube#5]
Nodes can't pull images on deployment when referencing the private registry (registry.dev.fullbacksystems.com)

Tried using both internal and external dns names. 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullback-website
  labels:
    app: fullback-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullback-website
  template:
    metadata:
      labels:
        app: fullback-website
    spec:
      hostAliases:
      - ip: "192.168.0.107"
        hostnames:
        - "registry.dev.fullbacksystems.com"
        - "docker-registry.default"
      containers:
      - name: fullback-website
        image: registry.dev.fullbacksystems.com/fullbacksystems-website:8523786c
        imagePullPolicy: Always
        ports:
        - containerPort: 80
```

Using the external dns name (registry.dev.fullbacksystems.com)

```
Aug 11 11:10:25 mico k3s[6292]: E0811 11:10:25.036322    6292 kuberuntime_image.go:50] Pull image "registry.dev.fullbacksystems.com/fullbacksystems-website:8523786c" failed: rpc error: code = NotFound desc = failed to pull and unpack image "registry.dev.
````

This is resolvable on the node:
```
$ nslookup registry.dev.fullbacksystems.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	registry.dev.fullbacksystems.com
Address: 192.168.0.107
```
But not within the cluster via coredns:

```
$ kubectl exec -i -t dnsutils -- nslookup registry.dev.fullbackystems.com
Server:		10.43.0.10
Address:	10.43.0.10#53

** server can't find registry.dev.fullbackystems.com: NXDOMAIN

command terminated with exit code 1
````

 Using internal dns name (docker-regsitry.default.svc.cluster.local):

```
Failed to pull image "docker-registry.default.svc.cluster.local/fullbacksystems-website:8523786c": rpc error: code = Unknown 
desc = failed to pull and unpack image "docker-registry.default.svc.cluster.local/fullbacksystems-website:8523786c": failed to resolve reference "docker-registry.default.svc.cluster.local/fullbacksystems-website:8523786c": failed to do request: Head https://docker-registry.default.svc.cluster.local/v2/fullbacksystems-website/manifests/8523786c: dial tcp: lookup docker-registry.default.svc.cluster.local: no such host
```
